### ISSUE TITLE
Bet box event image gradient

### ISSUE THREAD

**Issue by reubenbrr** [rwlumino/MaterialLounge#18]
http://i.imgur.com/GGiBUMQ.png

**Comment by ghost** [comment]
It's a quite easy fix.

```
.match
    position: relative

    .matchleft
         position: relative // To move it forward

    &::after
        content: ""
        display: block
        position: absolute
        bottom: 0
        top: 0
        right: (image width - gradient width)
        width: gradient width
        z-index: 0
        background-image: linear-gradient(to right, white, transparent)
```

I didn't test this code, but it should work, though you will have to find a workaround for prediction matches, as they have a little different structure. You will be able to target prediction matches by `a[href*="/predict"]`

Cheers.

**Comment by reubenbrr** [comment]
Thanks!

Will save me a bit of time
